services:
  telegram_bot:
    build: .
    container_name: secret-waves-telegram-bot-dev
    env_file:
      - .env
    command: uv run aiogram run polling src:dp --log-level debug --reload
    depends_on:
      - postgres
    volumes:
      - ./src/:/app/src/
      - ./migrations/:/app/migrations/

  admin:
    build: .
    container_name: secret-waves-admin-dev
    env_file:
      - .env
    command: sh -c "uv run alembic upgrade head && uv run uvicorn src:admin_app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./src/:/app/src/
      - ./migrations/:/app/migrations/

  postgres:
    image: postgres:17-bookworm
    container_name: secret-waves-postgres-dev
    restart: always
    environment:
      POSTGRES_USER: secret_waves_user
      POSTGRES_PASSWORD: secret_waves_password
      POSTGRES_DB: secret_waves_dev
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: