"""add s3_key field to Attachment model

Revision ID: 0054af00b447
Revises: e7f397674304
Create Date: 2025-07-04 20:05:29.536012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0054af00b447'
down_revision: Union[str, None] = 'e7f397674304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_attachments', sa.Column('s3_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_attachments', 's3_key')
    # ### end Alembic commands ###
