"""change name type field in Attachment model

Revision ID: e7f397674304
Revises: 487128097b9a
Create Date: 2025-07-04 17:05:25.566034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f397674304'
down_revision: Union[str, None] = '487128097b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # # Создаем новую колонку type как nullable
    # op.add_column('post_attachments', sa.Column('type', sa.String(length=20), nullable=True))

    # # Копируем данные из старой колонки attachment_type в новую колонку type
    # op.execute("UPDATE post_attachments SET type = attachment_type")

    # # Делаем новую колонку type не nullable
    # op.alter_column('post_attachments', 'type', nullable=False)

    # # Удаляем старую колонку attachment_type
    # op.drop_column('post_attachments', 'attachment_type')

    op.alter_column('post_attachments', 'attachment_type', new_column_name='type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # # Создаем старую колонку attachment_type как nullable
    # op.add_column('post_attachments', sa.Column('attachment_type', sa.String(length=20), autoincrement=False, nullable=True))

    # # Копируем данные из новой колонки type в старую колонку attachment_type
    # op.execute("UPDATE post_attachments SET attachment_type = type")

    # # Делаем старую колонку attachment_type не nullable
    # op.alter_column('post_attachments', 'attachment_type', nullable=False)

    # # Удаляем новую колонку type
    # op.drop_column('post_attachments', 'type')

    op.alter_column('post_attachments', 'type', new_column_name='attachment_type')

    # ### end Alembic commands ###
